//
//  AppLabels.swift
//  NeuroProMed
//
//  Created by Marin Novitchi on 30.05.2021.
//

import Foundation

enum AppLabels: String {
    
    case firstName = "First name textfield label"
    case lastName = "Last name textfield label"
    case bornAfter = "Born after picker label"
    case bornBefore = "Born before picker label"
    case birthDate = "Birth Date picker label"
    case address = "Address textfield label"
    case job = "Job textfield label"
    case patients = "Patients page title"
    case createPatient = "Create Patient page title"
    case editPatient = "Edit Patient page title"
    case filterPatients = "Filter Patients page title"
    case deletePatient = "Delete patient button label"
    case birthDateAndAge = "Birth date and age section header"
    case personalDetails = "Personal details section header"
    
    case addNewHoliday = "Add a new day off page title"
    case invalidHolidayMessage = "You have at least one appointment on that day"
    case holidays = "Holidays page title"
    case holidayAmount = "Holidays (number of days)"
    case email = "Email"
    case workingWeekends = "Working weekends"
    case doctorDetails = "Doctor Details section header"
    case editDoctor = "Edit Doctor page title"
    case isWorkingWeekends = "Is working weekends status"
    case isNotWorkingWeekends = "Is not working weekends status"
    case specialty = "Doctor specialty"
    
    case configuration = "Configuration section header"
    case biometricsPermissionDenied = "Biometrics pemission denied alert title"
    case biometricsPermissionRequest = "Reason for require permission"
    case biometricsUseTitle = "Use biometrics toggle label"
    case myProfile = "My Profile page title"
    case retryAuthentication = "Retry Authentication"
    case authentication = "Authentication"
    
    case removeFilter = "Remove filter"
    case filterAppointments = "Filter Appointments page title"
    case createAppointment = "Create appointment page title"
    case patient = "(The) Patient"
    case doctor = "(The) Doctor"
    case services = "(The) Services"
    case appointmentDateDisclosureLabel = "Appointment Date: (example)"
    case appointmentTimeDisclosureLabel = "Appointment Time: (example)"
    case appointmentTime = "Appointment Time section header"
    case dateFrom = "Date From"
    case dateTo = "Date To"
    case appSettings = "App Settings"
    case notificationAndCalendarPermissionDenied = "Notification or Calendar Pemission denied alert title"
    case appointment = "Appointment page title"
    case appointments = "Appointments page title"
    case notificationAndCalendar = "Notification and Calendar section header"
    case notificationAlert = "Notification alert"
    case addToCalendar = "Add to Calendar"
    case alertSetToX = "Notification alert text"
    case appointmentSavedToCalendarName = "Appointment Saved to (Calendar Name)"
    case investigation = "Investigation section header"
    case diagnosis = "Diagnosis section header"
    case serviceBill = "Service bill section header"
    case totalAmount = "Total for service"
    case for_prefix = "(appointment) For (a patient)"
    case with_prefix = "(appointment) With (a doctor)"
    case on_prefix = "(appointment) On (a particular date)"
    case at_prefix = "(appointment) At (a particular time)"
    case appointmentDetails = "Appointment Details"
    case cancelAppointment = "Cancel Appointment button label"
    case deleteAppointmentMessage = "Delete appointment warning message"
    case deletePatientMessage = "Delete patient warning message"
    case areYouSure_appointment = "Delete appointment warning title"
    case areYouSure_patient = "Delete patient warning title"
    case appointmentFor = "Doctor targeted notification message"
    case appointmentWith = "Patient targeted notification message"
    case editAppointment = "Edit Appointment page title"
    case add = "Add label"
    case new = "New label"
    case edit = "Edit label"
    case filter = "Filter label"
    case filterAction = "Filter action"
    case save = "Save label"
    case cancel = "Cancel label"
    case error = "Error label"
    case delete = "Delete label"
    case date = "Date label"
    case time = "Time picker label"
    case xTime = "Location time info"
    case unknownTimeLocation = "Unknown time location"
    case sortAscending = "To sort something ascending"
    case sortDescending = "To sort something descending"
    case older = "Older Appointment Section"
    case lastXDays = "lastXDays Appointment Section"
    case upcoming = "Upcoming value comment"
    
    case notificationNone = "Notification Schedule - None"
    case notification10min = "Notification Schedule - 10 minutes before"
    case notification15min = "Notification Schedule - 15 minutes before"
    case notification20min = "Notification Schedule - 20 minutes before"
    case notification30min = "Notification Schedule - 30 minutes before"
    case notification1h = "Notification Schedule - 1 hour before"
    case notification2h = "Notification Schedule - 2 hours before"
    case notification1d = "Notification Schedule - 1 day before"
    case notification2d = "Notification Schedule - 2 days before"
    case notification1w = "Notification Schedule - 1 week before"
    
    case loginAsDoctor = "Log in as a doctor"
    case loginAsPatient = "Login as a patient"
    case logout = "Log out"
    case wrongAuthState = "Wrong authentication state"
    case failToStoreKeychain = "Fail to store keychain"
    case failToUpdateSettings = "Fail to update settings"
    case failToDeleteKeychain = "Fail to delete keychain"
}
